### ISSUE TITLE
How do you install this on windows?

### ISSUE THREAD

**Issue by rubenchristoffer** [MartinSStewart/Lego-Loco-Remake#1]
Hi! I came across this when looking for ways to install Lego Loco and was wondering how you compile and run this on Windows.

**Comment by MartinSStewart** [comment]
Hi, this project was my attempt at recreating Lego Loco as a web browser game. I never finished it and it isn't really suitable for playing unfortunately.

I've gone ahead and updated the description to make that more clear, sorry about that.

**Comment by rubenchristoffer** [comment]
Ah, that's too bad. Luckily I got the original game to work on my Windows 10 machine using an alternate installer :)

**Comment by MartinSStewart** [comment]
Nice, have fun!
